# Generated by Django 4.1.3 on 2022-12-14 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=32)),
                ('advice', models.PositiveSmallIntegerField(choices=[(1, 'Weight Gain'), (2, 'Weight Loss'), (3, 'Endurance'), (4, 'Strength Gain')], default=1)),
                ('choice', models.PositiveSmallIntegerField(choices=[(1, 'Online'), (2, 'In Person')], default=1)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
