# Generated by Django 4.1.3 on 2022-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodapp', '0002_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='advice',
            field=models.CharField(choices=[('Weight Gain', 'Weight Gain'), ('Weight Loss', 'Weight Loss'), ('Endurance', 'Endurance'), ('Strength Gain', 'Strength Gain')], default='Weight Gain', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='choice',
            field=models.CharField(choices=[('Online', 'Online'), ('In Person', 'In Person')], default='Online', max_length=15),
        ),
    ]
