# Generated by Django 4.1.3 on 2022-12-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodapp', '0003_remove_booking_time_booking_advice_booking_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
